! Put your rules here in the format:
! old_biome > new_biome
! 
! Examples (remove ! in front of one to activate it):
! minecraft:dark_forest > minecraft:cherry_grove
! #minecraft:is_forest > minecraft:desert
! #terralith:skylands > null
minecraft:frozen_ocean > null
minecraft:deep_frozen_ocean > null
minecraft:jungle > null
minecraft:savanna > null
minecraft:savanna_plateau > null
minecraft:windswept_savanna > null
minecraft:ice_spikes > null
minecraft:sparse_jungle > null
minecraft:mangrove_swamp > null